### PR TITLE
vehicle additions, LAAT/c changes

### PR DESCRIPTION
**Pull request by jellyton255**
Added republic hover tank, codenamed TX-160

Added a Clone Wars version of the Headhunter.

Made changes to the LAAT/c so it doesn't fly retarded.

### CODE REVIEW

**Comment by Servius** [comment]
@jellyton69 Thanks for sending in your pull request! Please make sure that these use the EU spawnmenu rather than the official packs spawnmenu listing. Liam, Syph, and Doctor Jew tend to believe we overpopulate and end up swallowing up their uploads.

**Comment by jellyton255** [comment]
Alright, they're all in the right category now, although I do not know how to make any icons yet, so for now, they're blank.

**Comment by Servius** [comment]
Its actually quite simple. Find the model in the spawn menu, right click it and set its scale to 512x512 then modify the icon. Position it within the new window so it fills it then hit render. Once it looks fine ingame you can find the icon located in materials/spawnicons/modelpath

**Comment by Servius** [comment]
Then you take the icon and add it to the materials/entities/ folder in the base saving it as the same name as the entity in the actual entities folder

**Comment by jellyton255** [comment]
Ok, the icons are uploaded. @Servius

**Pull request merged**
